[pytest]
markers =
    create_booking: tests related to booking creation
    get_booking: tests related to getting bookings
    update_booking: tests related to updating bookings
    delete_booking: tests related to deleting bookings